// <auto-generated />
using System;
using EduMeilleurAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduMeilleurAPI.Migrations
{
    [DbContext(typeof(EduMeilleurAPIContext))]
    partial class EduMeilleurAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduMeilleurAPI.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("integer");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuestionTeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("QuestionTeacherId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectId = 2,
                            Title = "Vectors"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "My first Chat",
                            UserId = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 2,
                            Title = "My second Chat",
                            UserId = "11111111-1111-1111-1111-111111111111"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUser")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            Content = "SN5_IntroVectors_EN.md",
                            Title = "1.1 Introduction to Vectors"
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 1,
                            Content = "SN5_ComponentsandOrientation_EN.md",
                            Title = "1.2 Components and Orientation"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuestionTeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("QuestionTeacherId");

                    b.ToTable("Picture");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            FileName = "graph_plainVector.png",
                            MimeType = "image/png"
                        },
                        new
                        {
                            Id = 22,
                            FileName = "graph_vectorComponentsTriangle.png",
                            MimeType = "image/png"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.QuestionTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("QuestionTeacher");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Antoine-Brossard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lucille-Teasdale"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Introduction to advanced math concepts, focusing on functions, trigonometry, and problem-solving for science pathways.",
                            Name = "SN4",
                            Type = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Prepares students for post-secondary science programs with calculus basics, advanced algebra, and physics applications.",
                            Name = "SN5",
                            Type = "Math"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Practical mathematics for daily life: statistics, financial math, geometry, and measurement.",
                            Name = "CST4",
                            Type = "Math"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Continues CST4 with emphasis on budgeting, probability, and applied problem-solving.",
                            Name = "CST5",
                            Type = "Math"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Math for technical and science careers: algebra, systems of equations, and basic trigonometry.",
                            Name = "TS4",
                            Type = "Math"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Expands on TS4 with more complex functions, analytic geometry, and preparation for college science programs.",
                            Name = "TS5",
                            Type = "Math"
                        },
                        new
                        {
                            Id = 7,
                            Description = "General science covering biology, chemistry, and physics fundamentals through hands-on experiments.",
                            Name = "ST",
                            Type = "Science"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Science and technology with enriched content for students aiming at advanced science or technical studies.",
                            Name = "STE",
                            Type = "Science"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Study of matter, chemical reactions, stoichiometry, and laboratory techniques.",
                            Name = "Chimie",
                            Type = "Science"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Exploration of motion, forces, energy, and waves, with emphasis on practical experiments.",
                            Name = "Physique",
                            Type = "Science"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("IQPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<int?>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SchoolId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "339d1e38-c9af-48e5-86de-8e5b43b9c327",
                            Email = "2ariasat@gmail.com",
                            EmailConfirmed = false,
                            IQPoints = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "2ARIASAT@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEKnYiXvYgeRQT2HOIpD/RsZTkZEuxuL02rLcg04XCmfVZ86mfMUb7Z5D5nmfXQwhCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ed6d73e-dc90-4deb-8007-6126979b595c",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111112",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2e6158de-f06c-4072-bb1c-139c8e66e212",
                            Email = "bobibo@mail.com",
                            EmailConfirmed = false,
                            IQPoints = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOBIBO@MAIL.COM",
                            NormalizedUserName = "ROBERT LEBOIS",
                            PasswordHash = "AQAAAAIAAYagAAAAENVvTqmYC7JBlCJsKVdoESJsGPagBXep22gHCiXdC7mSLjBVdgnnXJFvLPipZ94SJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1d1bd6a-048d-4494-b8a4-24607c87a9d3",
                            TwoFactorEnabled = false,
                            UserName = "Robert Lebois"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111113",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11c8d6f0-bdfd-4df0-bb85-dc3eb9a5a930",
                            Email = "hmmm@mail.com",
                            EmailConfirmed = false,
                            IQPoints = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "HMMM@MAIL.COM",
                            NormalizedUserName = "JEROME LAPLANTE",
                            PasswordHash = "AQAAAAIAAYagAAAAEAUFCbypvdeGXZ4Ez7Dnk6bdw+kompLcyTjneUO7BVfdGowP3EoNOVRBqFIOlcZWzQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f0f0978c-a314-4397-81de-03c73b0d46b4",
                            TwoFactorEnabled = false,
                            UserName = "Jerome Laplante"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111114",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45dd391d-e92d-4184-ae1d-591742cb8db2",
                            Email = "teacher3@mail.com",
                            EmailConfirmed = false,
                            IQPoints = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEACHER3@MAIL.COM",
                            NormalizedUserName = "EMILY TREMBLAY",
                            PasswordHash = "AQAAAAIAAYagAAAAEB0xWFkQzVtL084wenLwqkH4n3145hDScP38tKiV8guu9xFZjNWSgW03+YGwv6fo/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "72426117-cd4e-4b0d-a1b6-52097831f1c0",
                            TwoFactorEnabled = false,
                            UserName = "Emily Tremblay"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111115",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f6b27ed-2f16-435b-94ff-df05a2bb1365",
                            Email = "teacher4@mail.com",
                            EmailConfirmed = false,
                            IQPoints = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "teacher4@MAIL.COM",
                            NormalizedUserName = "TYRONE ROCHELIEU",
                            PasswordHash = "AQAAAAIAAYagAAAAEGGsuV9VDb+F2oePcWyA1vlSfQka4if9X3GZlPc7SgzJos8s2FGqjIskvR5xJQKOJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fa4bcf46-5662-4e27-974f-1c7ff063db22",
                            TwoFactorEnabled = false,
                            UserName = "Tyrone Rochelieu"
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111116",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "23b6a824-c8a4-4253-8d4d-09b627fa6fd4",
                            Email = "teacher5@mail.com",
                            EmailConfirmed = false,
                            IQPoints = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "teacher5@MAIL.COM",
                            NormalizedUserName = "SARAH LAIDE",
                            PasswordHash = "AQAAAAIAAYagAAAAEKD9hKi32WJdbmTNX6Bt0tGNX2JJ53iNl5i1CwFoNab5YbA1nSI7tGOpcgi2x5lLew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e06cf7c6-7300-4d12-b506-d3fb44e8c859",
                            TwoFactorEnabled = false,
                            UserName = "Sarah Laide"
                        });
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "teacher",
                            NormalizedName = "TEACHER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111111",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111112",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111113",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111114",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111115",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "11111111-1111-1111-1111-111111111116",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Attachment", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Feedback", "Feedback")
                        .WithMany("Attachments")
                        .HasForeignKey("FeedbackId");

                    b.HasOne("EduMeilleurAPI.Models.QuestionTeacher", "QuestionTeacher")
                        .WithMany("Attachments")
                        .HasForeignKey("QuestionTeacherId");

                    b.Navigation("Feedback");

                    b.Navigation("QuestionTeacher");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Chapter", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Chat", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.ChatMessage", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Exercise", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Chapter", "Chapter")
                        .WithMany("Exercises")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Feedback", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.User", "user")
                        .WithMany("Feedbacks")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Notes", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Chapter", "Chapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Picture", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Feedback", "Feedback")
                        .WithMany("Pictures")
                        .HasForeignKey("FeedbackId");

                    b.HasOne("EduMeilleurAPI.Models.QuestionTeacher", "QuestionTeacher")
                        .WithMany("Pictures")
                        .HasForeignKey("QuestionTeacherId");

                    b.Navigation("Feedback");

                    b.Navigation("QuestionTeacher");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.QuestionTeacher", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.User", "user")
                        .WithMany("Questions")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.User", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Video", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.Chapter", "Chapter")
                        .WithMany("Videos")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduMeilleurAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EduMeilleurAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Chapter", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Notes");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Feedback", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.QuestionTeacher", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.School", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("EduMeilleurAPI.Models.User", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Feedbacks");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
